[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc2022"
path = "src/lib.rs"

[dependencies]
itertools = "0.10.5"
regex = "1.7.0"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false